### PR TITLE
Services (Mark,Clazz,Pupil)

### PR DESCRIPTION
**Pull request by zasamen**

### CODE REVIEW

**Comment by mbarouski** [comment]
not close pull requests

**Comment by zasamen** [comment]
ok

**Comment by mbarouski** [comment]
late:)

**Comment by mbarouski** [comment]
Two commits from this PR are in another PR with other commits, this PR is not useful.

**Comment by zasamen** [comment]
why?

**Comment by zasamen** [comment]
How can i delete pr?

**Comment by mbarouski** [comment]
I don't know

**Pull request closed without merging**
